name: Release ZenFTP

on:
  push:
    tags:
      - 'v*' # e.g., v1.0.0

permissions:
    contents: write

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Extracting changelog for version $VERSION"

          CHANGELOG=$(awk "/## \\[$VERSION\\]/ {flag=1; next} /^## \\[/ {flag=0} flag" CHANGELOG.md | sed '/^$/d')
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Package VS Code extension
        run: |
          npm install -g vsce
          vsce package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "ZenFTP ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Code Marketplace
        run: vsce publish --pat ${{ secrets.VSCE_TOKEN }}
